config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#index'
  
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/user.rb
class User < ApplicationRecord
    default_scope -> { order(created_at: :desc) }
    
    # Validations
    validates_presence_of :name, :status, :phone
    validates :email, presence: true, length: { maximum: 50, minimum: 5 },
                        uniqueness: { case_sensitive: false },
                        format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'Email invalid' }


    def self.search(search)
        if search
            @parameter = search.downcase
            where('name LIKE ?', "%#{@parameter}%")
        else
            all 
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_user, only: %i[destroy edit update]

    def index
      if params[:search].blank?
        @users = User.all.order(sort_column + " " + sort_direction).paginate(:per_page => 25, :page => params[:page])
      else
        @parameter = params[:search].downcase
        @users = User.all.where("lower(name) LIKE :search", search: "%#{@parameter}%").order(sort_column + " " + sort_direction).paginate(
                    page: params[:page], per_page: 25)
      end
      @user = User.new
    end

    def new
        @user = User.new
        respond_to do |format|
          format.html
          format.js
        end
    end

    def create 
      index
      @user = User.new(user_params)
        respond_to do |format|
          if @user.save
            format.html { redirect_to users_path }
            format.js
          else
            format.html { redirect_to users_path }
          end
      end
    end

    def edit
    end

    def update
        @user.update(user_params)
        respond_to do |format|
            if @user.update(user_params)
              index
              format.html { redirect_to users_path, notice: 'User successfully updated' }
              format.js
            else
              format.html { redirect_to users_path }
            end
        end
    end

    def destroy
        @user.destroy
        respond_to do |format|
            format.html { redirect_to users_path, notice: 'User deleted' }
            # format.js
        end
    end

    private

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :email, :title, :phone, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
      title ||= column.titleize
      css_class = column == sort_column ? "current #{sort_direction}" : nil
      direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
      # link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
      link_to title, params.merge(:sort => column, :direction => direction, :page => nil).permit(:sort, :direction, :page), {:class => css_class}
    end
    # def sortable(column, title = nil)
    #   title ||= column.titleize
    #   css_class = column == sort_column ? "current #{sort_direction}" : nil
    #   direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    #   link_to title, {:sort => column, :direction => direction}, {:class => css_class}
    # end
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebspoonsTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>

  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_edit.html.erb
<div class="modal-box">
      <div class="modal-header">
          <h3 class="title modal-title">Editing user</h3>
          <span class="close">&times;</span>
      </div>
      <div class="form-box">
        <%= render 'form', user: @user %> 
      </div>
</div>
  

app/views/users/_form.html.erb
<%= form_for(@user, remote: true, html: { data: { modal: true } }) do |form| %>
    <div class="form-inputs">
        <%= form.text_field :name, id: :name, placeholder: "Name", class: 'input'  %>
        <%= form.email_field :email, id: :email, placeholder: "Email", class: 'input' %>
        <%= form.text_field :title, id: :title, placeholder: "Title", class: 'input' %>
        <%= form.telephone_field :phone, id: :phone, placeholder: "Phone", class: 'input' %>
        <%= form.select :status, ["active", "inactive"], class: 'input' %>
    </div>
    <div class="form-button">
        <%= form.submit %>
    </div>
<% end %>

app/views/users/_new.html.erb
<div class="modal-box">
      <div class="modal-header">
          <h3 class="title modal-title">Create new user</h3>
          <span class="close">&times;</span>
      </div>
      <div class="form-box">
        <%= render 'form', user: @user %> 
      </div>
</div>
  

app/views/users/_users.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<table class="pretty">
      <tr>
        <th><%= sortable "name" %></th>
        <th><%= sortable "email" %></th>
        <th><%= sortable "title" %></th>
        <th><%= sortable "phone" %></th>
        <th><%= sortable "status" %></th>
      </tr>

      <% for user in @users %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.title %></td>
          <td><%= user.phone %></td>
          <% if user.status === 'active' %>
            <td class="status_active">Active</td>
          <% else %>
            <td class="status_inactive">Inactive</td>
          <% end %>
          <td class=""><%= link_to 'edit', edit_user_path(user), remote: true, class: 'btn mr-4', data: { modal: true }%></td>
          <td class=""><%= link_to 'delete', user, remote: true, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn danger" %></td>
        </tr>
      <% end %>
</table>

<section class="digg_pagination">
      <%= will_paginate @users %>
</section>

app/views/users/create.js.erb
$('#users').html("<%= j render "users" %>")
$('.display-modal').removeClass('display-modal').addClass('hide-modal');

app/views/users/edit.js.erb
$(function(event) {    
    $("#modal-window").find(".modal-content").html("<%= j (render 'edit') %>");
    $('.hide-modal').removeClass('hide-modal').addClass('display-modal');
});

$(document).on('click','.close',function() {
    $('.display-modal').removeClass('display-modal').addClass('hide-modal');
});

app/views/users/index.html.erb
<section class="header">
    <h1>Webspoons</h1>
    <h4>A list of users</h4>
</section>

<section class="container">

  <%= link_to 'Add user', new_user_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-lg'}  %>
  <div id="modal-window">
    <div class="modal-content hide-modal"></div>
  </div>

  
  <div id="search">
    <%= form_tag users_path, :method => 'get', :id => "users_search" do %>
      <%= hidden_field_tag :direction, params[:direction] %>
      <%= hidden_field_tag :sort, params[:sort] %>
      <div class="search">
        <p>
          <%= text_field_tag :search, params[:search], class: "input" %>
          <%= submit_tag "Search", :name => nil, class: "btn search_btn" %>
        </p>
      </div>
      <div id="users"><%= render 'users' %></div>
    <% end %>
  </div>
</section>

app/views/users/index.js.erb
$("#users").html("<%= escape_javascript(render("users")) %>");

app/views/users/new.js.erb
$(function(event) {    
    $("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
    $('.hide-modal').removeClass('hide-modal').addClass('display-modal');
});

$(document).on('click','.close',function() {
    $('.display-modal').removeClass('display-modal').addClass('hide-modal');
});



    

app/views/users/update.js.erb
$('#users').html("<%= j render "users" %>")
$('.display-modal').removeClass('display-modal').addClass('hide-modal');